[package]
name = "ironcc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
static_header = []

[dependencies]

[dev-dependencies]
pretty_assertions = "1.2"
insta = "1.15.0"
